# Gradle runtime
org.gradle.jvmargs=-Xmx2G -Dfile.encoding=UTF-8
org.gradle.parallel=true
org.gradle.configuration-cache=false
org.gradle.java.home=C:/Program Files/Java/jdk-25

# Fabric toolchain
minecraft_version=26.2
loader_version=0.19.3
fabric_api_version=0.155.2+26.2
loom_version=1.17.17

# Project identity
mod_version=0.1.0
maven_group=io.github.zcpu954861
archives_base_name=Pixel-Tzz-Pro

